config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  root to: 'pages#home'
  patch '/reservations/:id', to: 'reservations#accept', as: 'accept'
  patch '/reservations/:id', to: 'reservations#decline', as: 'decline'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update] do
    get '/notification', to: 'reservations#notify', as: 'notify'
  end
  resources :places do
    resources :reservations, only: [ :create ]
    resources :reviews, only: [ :create ]
  end
  resources :reservations, only: [] do
    member do
      patch :accept
      patch :decline
    end
  end



end

app/models/user.rb
require 'date'

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :places, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :reservations_as_owner, through: :places, source: :reservations, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :reviews_as_owner, through: :places, source: :reviews, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
  mount_uploader :avatar, PhotoUploader
  mount_uploader :band_photo, PhotoUploader

  def future_reservations_as_owner
    self.reservations_as_owner.select { |resa| resa unless resa.date.past?}
  end

  def pending_reservations_as_owner
    @pending_reservations_as_owner = self.future_reservations_as_owner.select {|resa| resa if resa.status == "pending"}
    if @pending_reservations_as_owner.length > 0
      @pending_reservations_as_owner.sort_by { |resa| resa.date}
    else
      []
    end
  end

  def today_reservations_as_owner
    @today = Date.today
    @today_reservations_as_owner = self.future_reservations_as_owner.select {|resa| resa if (resa.date.month == @today.month && resa.date.day == @today.day && resa.date.year == @today.year) }
    return @today_reservations_as_owner.select {|resa| resa if resa.status.downcase == "accepted"}
  end

  def all_reservations_as_owner
    @all_reservations_as_owner = self.reservations_as_owner - self.pending_reservations_as_owner - self.today_reservations_as_owner
    return @all_reservations_as_owner.sort_by { |resa| resa.date}
  end

  def future_reservations
    self.reservations.select { |resa| resa unless resa.date.past?}
  end

  def past_accepted_reservations
    past_reservations = self.reservations - self.future_reservations
    return past_reservations.select { |resa| resa if resa.status.downcase == "accepted"}
  end

  def pending_reservations
    @pending_reservations = self.future_reservations.select {|resa| resa if resa.status == "pending"}
    return @pending_reservations.sort_by { |resa| resa.date} if @pending_reservations.length > 0
  end

  def today_reservations
    @today = Date.today
    return self.reservations.select {|resa| resa if (resa.date.month == @today.month && resa.date.day == @today.day && resa.date.year == @today.year) && resa.status.downcase != "declined" }
  end

  def all_reservations
    all_reservations = self.reservations - self.today_reservations
    all_reservations.select {|resa| resa unless resa.date.past?}
    return all_reservations.sort_by { |resa| resa.date}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :pending_reservations_as_owner]

  def show
    authorize @user
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    @user.update(user_params)
    raise
    if @user.save
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :avatar, :band_manager, :band_name, :number_of_musicians, :music_type, :band_description, :band_photo)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/edit.html.erb
<div class="log-in-container">
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Edit profile</h1>
      <%= simple_form_for @user do |f| %>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :avatar %>
        <%= f.input :avatar_cache, as: :hidden %>
        <%= f.input :band_manager, as: :boolean, checked_value: true, unchecked_value: false %>
        <%= f.input :band_name %>
        <%= f.input :number_of_musicians %>
        <%= f.input :music_type %>
        <%= f.input :band_description %>
        <%= f.input :band_photo %>
         <%= f.input :band_photo_cache, as: :hidden %>
        <%= f.submit "Save", class: "btn btn-info btn-full-width" %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/users/group_show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url('<%= cl_image_path @user.band_photo %>')">
</div>

<div class="container">
  <div class="row">

    <div class="col-md-8">
      <div class="flat-info">
        <% if @place.user == current_user %>
          <div class="price">
            <h3><strong><%= @place.price %>€</strong></h3>
            <p>per hour</p>
          </div>
        <% end %>
        <div class="recap">
          <p class="category"><%= @place.category.upcase %></p>
          <div class="main-info">
            <div class="title">
              <h2><strong><%= @place.name %></strong></h2>
              <p><%= @place.address %></p>
            </div>
            <div class="user text-center">
              <% if @place.user == current_user %>
                <%= link_to "Edit", edit_place_path(@place), class: "btn btn-info" %>
              <% else %>
                <% if @place.user.avatar.present? %>
                  <%= cl_image_tag @place.user.avatar, class: "avatar-large" %>
                <% else %>
                  <p><img class="avatar-large" src="http://www.clker.com/cliparts/m/3/I/C/c/2/grey-silhouette-of-man-hi.png" alt="silhouette"></p>
                <% end %>
                <p><%= @place.user.first_name %></p>
              <% end %>
            </div>
          </div>
          <div class="details">
            <p><i class="fa fa-users"></i> <%= @place.stage_capacity %></p>
            <% if @place.equipped %>
              <p><i class="fa fa-microphone"></i> <%= "fully-equipped" %></p>
            <% else %>
              <p><i class="fa fa-microphone-slash"></i> <%= "not equipped" %></p>
            <% end %>
          </div>
        </div>
        <div class="description">
          <p><%= @place.description %></p>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <% if @place.user == current_user %>
        <h3>Reservations</h3>
        <% if @place.reservations.where(status: "pending").count > 0%>
          <div class="pending-or-answered-reservations">
            <% @place.reservations.order(:date).each do |reservation| %>
              <% if reservation.status == "pending" %>
                <div class="recap-reservation">
                  <div class="request">
                    <p class="pending"><%= reservation.status.upcase %></p>
                    <h4><strong><%= reservation.price %>€</strong></h4>
                  </div>
                  <div class="date">
                    <h5><strong><%= reservation.date.strftime("%B %d, %Y %I:%M %p") %></strong></h5>
                    <p>Duration: <%= reservation.duration %>h</p>
                  </div>
                  <div class="change-status">
                    <p><%= link_to "ACCEPT", accept_reservation_path(reservation), class: "btn btn-success btn-accept", method: :patch %></p>
                    <p><%= link_to "DECLINE", decline_reservation_path(reservation), class: "btn btn-danger btn-decline", method: :patch %></p>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
        <% if @place.reservations.where.not(status: "pending").count > 0%>
          <div class="pending-or-answered-reservations">
            <% @place.reservations.order(:date).each do |reservation| %>
              <% if reservation.status != "pending" %>
                <div class="recap-reservation">
                  <div class="request">
                    <p class="<%= reservation.status %>"><%= reservation.status.upcase %></p>
                    <h4><strong><%= reservation.price %>€</strong></h4>
                  </div>
                  <div class="date">
                    <h5><strong><%= reservation.date.strftime("%B %d, %Y %I:%M %p") %></strong></h5>
                    <p>Duration: <%= reservation.duration %>h</p>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>



      <% else %>
        <h3>Book now</h3>
        <div class="reservation">
          <div class="price">
            <h4><strong><%= @place.price %>€</strong></h4>
            <p>per hour</p>
          </div>
          <%= simple_form_for [@place, @reservation] do |f| %>
            <%= f.input :date, as: :string, placeholder: "April 20, 2020 9:00 PM", input_html: {class: "datepicker"} %>
            <%= f.input :duration, placeholder: "4 (hours)" %>
            <%= f.submit "Make a booking request", class: "btn btn-info btn-full-width btn-yellow" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="dashboard-container">

  <!-- Cas 1: un user est place owner -->

  <% if !@user.band_manager %>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="profil">
          <div class="profil-pic">
            <% if @user.avatar.present? %>
              <%= cl_image_tag(@user.avatar, class:"avatar-very-large", crop: :fill) %>
              <p class="text-center"><%= @user.first_name %> <%= @user.last_name %></p>
            <% else %>
              <%= cl_image_tag("http://www.castlehearing.co.uk/wp-content/uploads/2016/03/profile-placeholder.jpg", class:"avatar-very-large", crop: :fill) %>
              <% if @user.first_name.present? && @user.last_name.present? %>
                <p class="text-center"><%= @user.first_name %> <%= @user.last_name %></p>
              <% end %>
            <% end %>
            <%= link_to "Edit profile", edit_user_path(@user), class: "btn btn-info" %>

          </div>
          <div class="profil-places">
            <% @user.places.each do |place| %>
              <div class="mini-card">
                <div class="mini-card-photo" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path place.photo, height: 150, width: 200,crop: :fill %>')"> </div>
                <div class="mini-card-content">
                  <div class="mini-place-name">
                    <h3><%= link_to place.name, place_path(place), target: "blank" %></h3>
                  </div>
                  <div class="mini-place-price">
                    <p><em><%= place.price %>€ per hour</em></p>
                  </div>

              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-9">
        <div class="pending-reservations reservations">
          <h4>Pending reservations:</h4>
          <% @user.pending_reservations_as_owner.each do |reservation| %>
            <%= render "shared/resa_card", reservation: reservation %>
          <% end %>
          <%= "No pending reservations." if @user.pending_reservations_as_owner == [] %>
        </div>

        <div class="today-reservations reservations">
          <h4>Today's reservations:</h4>
          <% @user.today_reservations_as_owner.each do |reservation| %>
            <%= render "shared/resa_card", reservation: reservation %>
          <% end %>
          <%= "No reservations today." if @user.today_reservations_as_owner == [] %>
        </div>

        <div class="all-reservations reservations">
          <h4>All my reservations:</h4>
          <% @user.all_reservations_as_owner.each do |reservation| %>
            <%= render "shared/resa_card", reservation: reservation %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <!-- Cas 2: un user est group manager -->
  <% else %>


  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="profil-band">
          <div class="profil-pic">
            <% if @user.avatar.present? %>
              <%= cl_image_tag(@user.avatar, class:"avatar-very-large", crop: :fill) %>
              <p class="text-center"><%= @user.first_name %> <%= @user.last_name %></p>
            <% else %>
              <%= cl_image_tag("http://www.castlehearing.co.uk/wp-content/uploads/2016/03/profile-placeholder.jpg", class:"avatar-very-large", crop: :fill) %>
            <% end %>
            <%= link_to "Edit profile", edit_user_path(@user), class: "btn btn-info" %>
          </div>
          <div class="band-card">
          </div>
        </div>
      </div>

      <div class="col-md-9">
        <div class="today-reservations-band reservations">
          <h3>Today's reservations:</h3>
          <% @user.today_reservations.each do |reservation| %>
            <%= render "shared/resa_card", reservation: reservation %>
          <% end %>
          <%= "No reservations today." if @user.today_reservations == [] %>
        </div>

        <div class="all-reservations-band reservations">
          <h3>All my reservations:</h3>
          <% if @user.reservations.length >= 1 %>
            <% @user.all_reservations.each do |reservation| %>
              <%= render "shared/resa_card", reservation: reservation %>
            <% end %>
            <% else %>
            <%= "No reservations."  %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>