config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  root to: 'pages#home'
  patch '/reservations/:id', to: 'reservations#accept', as: 'accept'
  patch '/reservations/:id', to: 'reservations#decline', as: 'decline'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update] do
    get '/notification', to: 'reservations#notify', as: 'notify'
  end
  resources :places do
    resources :reservations, only: [ :create ]
    resources :reviews, only: [ :create ]
  end
  resources :reservations, only: [] do
    member do
      patch :accept
      patch :decline
    end
  end



end

app/views/shared/_card.html.erb
<%= link_to place_path(place), target: "_blank" do %>
  <div class="card">
    <%= cl_image_tag place.user.avatar, class: "avatar card-avatar"%>
    <div class="card-photo" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path place.photo, height: 300, width: 400,crop: :fill %>')"> </div>
    <div class="card-content">
      <div class="place-category">
        <p><%= place.category.upcase %></p>
      </div>
      <div class="place-rating">
        <% place.average_rating.times do %>
         <span><i class="fas fa-star"> </i></span>
        <% end %>
      </div>
      <div class="place-name">
        <h3><%= place.name %></h3>
      </div>
      <div class="place-price">
        <p><em><%= place.price %>€ per hour</em></p>
      </div>
  </div>
</div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- <div class="footer-push"></div> -->

<div class="footer">
  <div class="footer-copyright">
    © AirJam has been made @<span><a href="https://www.lewagon.com/fr", target="_blank", id="wagon-link">Le Wagon</a></span> in march 2018 by Nina, Kenza, Marion and Elsa.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>


      <div class="input-group <%= "hidden" if params[:action] == "home" %>">
        <div class="input-group">
          <%= form_tag places_path, class: "flexbox",method: :get do %>
            <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "e.g. Paris, jazz, ..." %>
            <%= submit_tag :Search, class: "btn btn-info"  %>
          <% end %>
        </div>
      </div>

      <!-- Links when logged in -->

<!--       TO DO about link -->

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <div class="notification-holder">
            <% if current_user.avatar.present? %>
              <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <% else %>
              <%= image_tag "http://www.clker.com/cliparts/m/3/I/C/c/2/grey-silhouette-of-man-hi.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <% end %>
  <!-- Adding notification on avatar -->
                <div class="transparent notification notification-position text-center"
                data-user-id="<%= current_user.id %>">
                  <%= current_user.pending_reservations_as_owner.length %>
                </div>

<!-- Start of dropdown -->
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to user_path(current_user) do %><%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <% if !current_user.band_manager %>
                <li><%= link_to t(".new", default: "Add a Place"), new_place_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
              <% end %>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %><%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>

    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".new", default: "Add a Place"), new_place_path, class: "navbar-wagon-item navbar-wagon-link" %>
<!--       TO DO about link -->
      <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to t(".new", default: "Add a Place"), new_place_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
</div>

<div class="navbar-push"></div>

app/views/shared/_notification.html.erb
<div id="notification" class="notification-position text-center">
  <%= current_user.pending_reservations_as_owner.length %>
</div>

app/views/shared/_resa_card.html.erb
<div class="resa-card">
  <div class="resa-details">
    <h5><strong><%= link_to reservation.place.name, place_path(reservation.place), class: "bar-link" %></strong> - <strong><%= reservation.price %>€</strong></h5>
    <h5><strong><%= reservation.date.strftime("%B %d, %Y %I:%M %p") %></strong></h5>
    <p>Duration: <%= reservation.duration %>h</p>
  </div>
  <div class="resa-status">
    <% if reservation.user == current_user && reservation.date.past? %>
      <p class="<%= reservation.status %>"><%= link_to "LEAVE A REVIEW", place_path(reservation.place) %></p>
    <% elsif reservation.place.user == current_user && reservation.date.past? %>
      <p class="<%= reservation.status %>"><%= link_to "REVIEWED", place_path(reservation.place) %></p>
    <% else  %>
      <p class="<%= reservation.status %>"><%= reservation.status.upcase %></p>
    <% end %>
  </div>
  <div class="user text-center">
    <% if reservation.user == current_user %>
      <% if reservation.place.user.avatar.present? %>
        <%= cl_image_tag reservation.place.user.avatar, class: "avatar-large" %>
      <% else %>
        <p><img class="avatar-large" src="http://www.clker.com/cliparts/m/3/I/C/c/2/grey-silhouette-of-man-hi.png" alt="silhouette"></p>
      <% end %>
      <p><%= reservation.place.user.first_name %></p>
    <% else %>
      <% if reservation.user.avatar.present? %>
        <%= cl_image_tag reservation.user.avatar, class: "avatar-large" %>
      <% else %>
        <p><img class="avatar-large" src="http://www.clker.com/cliparts/m/3/I/C/c/2/grey-silhouette-of-man-hi.png" alt="silhouette"></p>
      <% end %>
      <p><%= reservation.user.first_name %></p>
    <% end %>
  </div>
</div>